name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  
  pull_request:
    branches:
      - main
  
  # Weekly schedule (Sunday at 6:15 UTC)
  schedule:
    - cron: '15 6 * * 0'
  
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch event info
        run: |
          echo "triggering event: ${{ github.event_name }}"
          echo "triggering branch: ${{ github.ref }}"
          
      - uses: actions/checkout@v4
      
      - name: List files in the repo
        run: |
          echo "Repo contains:"
          tree
